# Use root/example as user/password credentials

version: "3"
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
    depends_on:
      - db
      
  eyft:
    image: eyft/backend-server-monolit
    restart: always
    ports: 
      - 8080:8080
    environment:
      spring_datasource_url: jdbc:mysql://db:3306/db_eyft?createDatabaseIfNotExist=true
      photo_directory_path: /CWPhotos
      spring_kafka_bootstrap_servers: kafka:9092
      spring_datasource_username: root
    depends_on:
      - kafka
      - db
    links:
      - kafka:kafka
      
  eyft-frontend:
    image: eyft/frontend-server-monolit
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      - eyft
    links:
      - eyft:eyft